name: eofs-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - numpy
  - xarray
  - matplotlib
  - scipy
  - cartopy
  - xeofs
  - eofs
  - intake
  - intake-esm
  - fsspec
  - nc-time-axis
  - gcsfs
  - mystmd
  - cftime
  - pydap
  - sphinx-pythia-theme
